[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv', 'gcc']
aptPkgs = ['default-libmysqlclient-dev', 'libpq-dev', 'pkg-config']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[start]
cmd = 'source /opt/venv/bin/activate && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file -'
